name: Upstream Sync
permissions:
  contents: write

on:
  schedule:
    - cron: "0 */3 * * *" # every day
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: Calcium-Ion/new-api
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Reset .github/workflows folder
        run: git checkout HEAD -- .github/workflows

      - name: Check for changes
        id: git-diff
        run: |
          changed_files=$(git diff-tree --no-commit-id --name-only -r HEAD)
          if [[ -z "$changed_files" ]]; then
            echo "::set-output name=changes::false"
          else
            echo "::set-output name=changes::true"
          fi

      - name: Update build.txt with current time
        run: |
          echo $(date) > .github/workflows/build.txt
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add -f .github/workflows/build.txt
          git commit -m "Update build.txt with current time"
          git push


      - name: Trigger docker-image workflow
        if: steps.git-diff.outputs.changes == 'true'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/KenGrofork/NineAIQuickDeploy/dispatches \
          -d '{"event_type": "trigger-docker-image"}'
